### ISSUE TITLE
Some question with source code

### ISSUE THREAD

**Issue by Thewillman** [HanjieChen/REV#1]
I don't know whether is transformers problem or our code problem
When I create conda environment follow .yml,start training g,it returns seems an uneditable problem
Traceback (most recent call last):
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/suyisong/REV/src/rev/rev_train.py", line 454, in <module>
    main()
  File "/data/suyisong/REV/src/rev/rev_train.py", line 422, in main
    eval_dataset=eval_dataset,
  File "/data/suyisong/REV/src/rev/generative.py", line 575, in train
    loss = loss_fnc(args, batch, model)
  File "/data/suyisong/REV/src/rev/rev_train.py", line 114, in get_loss
    input_ids, attention_mask=input_mask, decoder_input_ids=decoder_input_ids, use_cache=False
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/transformers/modeling_t5.py", line 1158, in forward
    return_dict=return_dict,
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/transformers/modeling_t5.py", line 766, in forward
    output_attentions=output_attentions,
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/transformers/modeling_t5.py", line 529, in forward
    output_attentions=output_attentions,
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/transformers/modeling_t5.py", line 436, in forward
    output_attentions=output_attentions,
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/transformers/modeling_t5.py", line 348, in forward
    q = shape(self.q(input))  # (bs, n_heads, qlen, dim_per_head)
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/suyisong/.conda/envs/revenv/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by HanjieChen** [comment]
Hi, it does not seem like a code problem. Please check whether your transformer is compatible with your Pytorch and Cuda versions. Thanks!
